version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_crud
      MYSQL_USER: MySQL80
      MYSQL_PASSWORD: NestJs_2025!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./test-backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./test-backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=mysql # ✅ CORRIGÉ : utilise le nom du service
      - DB_PORT=3306
      - DB_USERNAME=MySQL80 # ✅ CORRIGÉ : utilise l'utilisateur créé
      - DB_PASSWORD=NestJs_2025!
      - DB_DATABASE=test_crud
    depends_on:
      mysql:
        condition: service_healthy # ✅ Attend que MySQL soit prêt
    networks:
      - app-network

  frontend:
    build:
      context: ./test-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./test-frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
