import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header/Header";
import Footer from "@/components/layout/Footer";
import { Providers } from "@/config/ApolloProvider";
import { CircleBackground } from "@/components/common";
// import { ScreenSize } from "@/components/common/ScreenSize";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body
        className="antialiased min-h-screen flex flex-col"
        suppressHydrationWarning={true}
      >
        <Providers>
          {/* <ScreenSize /> */}
          <Header />
          <div className="flex-1">
            <CircleBackground>{children}</CircleBackground>
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
